services:
  octoeverywhere-bambu-connect:
    image: octoeverywhere/octoeverywhere:latest
    env_file: /etc/homelab/octoeverywhere/bambu_x1c_feanor.env
    environment:
        # Requried to set the docker conntainer in Bambu Connect mode.
      COMPANION_MODE: bambu
    volumes:
      - type: volume
        source: data
        target: /data
        volume:
          nocopy: true
          subpath: octoeverywhere/data

volumes:
  data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=terminal-dogma.local,nolock,soft,nfsvers=4
      device: :/mnt/DataPool/AppData
