services:
  awsdns:
    build:
      context: https://github.com/borzilleri/aws-dynamic-dns.git#:app
    volumes:
      - ./aws-dns/config.toml:/config.toml:ro
    secrets:
      - aws-credentials
  certbot:
    image: certbot/certbot:latest
    volumes:
      - /var/www/certbot/:/var/www/certbot/:rw
      - /etc/letsencrypt/:/etc/letsencrypt/:rw
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/:/etc/nginx/conf.d/:ro
      - /var/www/certbot/:/var/www/certbot/:ro
      - /etc/letsencrypt/:/etc/nginx/ssl/:ro
    healthcheck:
      test: curl --fail http://localhost/ping || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    ports:
      - 7878:7878
    volumes:
      - /etc/servarr/radarr/config:/config
      - central-dogma:/data
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    ports:
      - 6767:6767
    volumes:
      - /etc/servarr/bazarr/config:/config
      - central-dogma:/data
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    ports:
      - 9696:9696
    volumes:
      - /etc/servarr/prowlarr:/config
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    ports:
      - 8080:8080
    volumes:
      - /etc/servarr/sabnzbd:/config
      - central-dogma:/data

volumes:
  central-dogma:
    driver: local
    driver_opts:
      type: nfs
      o: addr=central-dogma.local,nolock,soft,nfsvers=4
      device: :/volume1/Media

secrets:
  aws-credentials:
    file: /etc/aws/aws-dns.json
