include:
  - ../common/networks.yaml

services:
  kobodl: # Port 5000
    image: ghcr.io/subdavis/kobodl:${VERSION:-latest}
    container_name: kobodl
    restart: unless-stopped
    labels:
      wud.watch: true
      wud.tag.include: '^\d+\.\d+\.\d+$'
      wud.link.template: 'https://github.com/subdavis/kobo-book-downloader/releases/tag/$${original}'
    volumes:
      - /opt/appdata/kobodl/data/kobodl.json:/home/kobodl.json
      - type: volume
        source: central-dogma
        target: /home/downloads
        volume:
          nocopy: true
          subpath: downloads/bookdrop
    command: --config /home/kobodl.json serve -h 0.0.0.0 -p 5000 --output-dir /home/downloads
    networks:
      - homelab

volumes:
  central-dogma:
    driver: local
    driver_opts:
      type: nfs
      o: addr=central-dogma.local,nolock,soft,nfsvers=4
      device: :/volume1/Media
