include:
  - ../common/networks.yaml
services:
  mealie:
    # Port 9000
    image: ghcr.io/mealie-recipes/mealie:v2.2.0
    container_name: mealie
    restart: unless-stopped
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - type: volume
        source: data
        target: /app/data
        volume:
          nocopy: true
          subpath: data
    # This should be a path to an env file with just the
    # POSTGRES_PASSWORD env var, containing the postgres password.
    # because the mealie dev is an absolute FUCKING MORON
    # who's too idiotic too implement the *_FILE pattern correctly
    # for docker secrets. What a fucking dipshit.
    env_file: /etc/homelab/mealie/postgres.env
    environment:
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: America/Los_Angeles
      # BASE_URL: https://mealie.yourdomain.com
      DB_ENGINE: postgres
      POSTGRES_DB: mealie
      POSTGRES_USER: mealie
      POSTGRES_SERVER: db
    networks:
      - default
      - homelab

  db:
    image: postgres:15
    container_name: mealie-db
    restart: unless-stopped
    user: "1000:1000"
    environment:
      POSTGRES_DB: mealie
      POSTGRES_USER: mealie
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
    volumes:
      - type: volume
        source: data
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
          subpath: postgresql15
    networks:
      - default
    secrets:
      - POSTGRES_PASSWORD

networks:
  default:

volumes:
  data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=terminal-dogma.local,nolock,soft,nfsvers=4
      device: :/mnt/Storage Pool 1/mealie-data

secrets:
  POSTGRES_PASSWORD:
    file: /etc/homelab/mealie/secrets/db_pass
