services:
  mealie:
    # Port 9000
    image: ghcr.io/mealie-recipes/mealie:v2.2.0
    container_name: mealie
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - mealie-data:/app/data/
      - type: volume
        source: data
        target: /app/data
        volume:
          nocopy: true
          subpath: data
    environment:
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZL: America/Los_Angeles
      # BASE_URL: https://mealie.yourdomain.com
      DB_ENGINE: postgres
      POSTGRES_DB: mealie
      POSTGRES_USER: mealie
      POSTGRES_SERVER: db
    depends_on:
      postgres:
        condition: service_healthy
    secrets:
      - POSTGRES_PASSWORD

  db:
    container_name: mealie-db
    image: postgres:15
    restart: unless-stopped
    volumes:
      - type: volume
        source: data
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
          subpath: db
    environment:
      POSTGRES_DB: mealie
      POSTGRES_USER: mealie
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3
    secrets:
      - POSTGRES_PASSWORD

volumes:
  data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=terminal-dogma.local,nolock,soft,nfsvers=4
      device: :/mnt/Storage Pool 1/mealie-data

secrets:
  POSTGRES_PASSWORD:
    file: /etc/homelab/mealie/secrets/db_pass
