include:
  - ../common/networks.yaml
services:
  broker:
    image: docker.io/library/redis:7
    container_name: paperless-broker
    restart: unless-stopped
    user: "1000:1000"
    volumes:
      - type: volume
        source: data
        target: /data
        volume:
          nocopy: true
          subpath: paperless/db/redis
    networks:
      - default

  db:
    image: docker.io/library/postgres:16
    container_name: paperless-db
    restart: unless-stopped
    user: "1000:1000"
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_pass
    volumes:
      - type: volume
        source: data
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
          subpath: paperless/db/postgres16
    networks:
      - default
    secrets:
      - db_pass
      - db_user

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless
    restart: unless-stopped
    depends_on:
      - db
      - broker
    user: "1000:1000"
    env_file: docker-compose.env
    environment:
      PAPERLESS_URL: https://paperless.sdf1.site
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_DBUSER_FILE: /run/secrets/db_user
      PAPERLESS_DBPASS_FILE: /run/secrets/db_pass
    volumes:
      - type: volume
        source: data
        target: /usr/src/paperless/data
        volume:
          nocopy: true
          subpath: paperless/data
      - type: volume
        source: data
        target: /usr/src/paperless/media
        volume:
          nocopy: true
          subpath: paperless/media
      - /opt/terminal_dogma/Paperless/export:/usr/src/paperless/export
      - /opt/terminal_dogma/Paperless/import:/usr/src/paperless/consume
    networks:
      - default
      - homelab
    secrets:
      - db_pass
      - db_user

volumes:
  data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=terminal-dogma.local,nolock,soft,nfsvers=4
      device: :/mnt/DataPool/AppData

networks:
  default:

secrets:
  db_pass:
    file: /etc/homelab/paperless/secrets/db_pass
  db_user:
    file: /etc/homelab/paperless/secrets/db_user
