services:
  broker:
    image: docker.io/library/redis:7
    container_name: paperless-broker
    restart: unless-stopped
    user: "1000:1000"
    volumes:
      - type: volume
        source: db_data
        target: /data
        volume:
          nocopy: true
          subpath: redis

  db:
    image: docker.io/library/postgres:16
    container_name: paperless-db
    restart: unless-stopped
    user: "1000:1000"
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
          subpath: postgresql
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_pass
    secrets:
      - db_pass
      - db_user

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-webserver
    restart: unless-stopped
    depends_on:
      - db
      - broker
    user: "1000:1000"
    volumes:
      - type: volume
        source: data
        target: /usr/src/paperless/data
        volume:
          nocopy: true
          subpath: data
      - type: volume
        source: data
        target: /usr/src/paperless/media
        volume:
          nocopy: true
          subpath: media
      - /terminal_dogma/paperless/export:/usr/src/paperless/export
      - /terminal_dogma/paperless/import:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_DBUSER_FILE: /run/secrets/db_user
      PAPERLESS_DBPASS_FILE: /run/secrets/db_pass
    secrets:
      - db_pass
      - db_user

volumes:
  db_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=terminal-dogma.local,nolock,soft,nfsvers=4
      device: :/mnt/AppDataPool/paperless-db
  data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=terminal-dogma.local,nolock,soft,nfsvers=4
      device: :/mnt/Storage Pool 1/paperless-data

secrets:
  db_pass:
    file: /etc/homelab/paperless/secrets/db_pass
  db_user:
    file: /etc/homelab/paperless/secrets/db_user
