services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    environment:
      HOMEPAGE_FILE_TAUTULLI_KEY: /run/secrets/tautulli_key
      HOMEPAGE_FILE_RADARR_KEY: /run/secrets/radarr_key
      HOMEPAGE_FILE_SONARR_KEY: /run/secrets/sonarr_key
      HOMEPAGE_FILE_BAZARR_KEY: /run/secrets/bazarr_key
      HOMEPAGE_FILE_SYNOLOGY_USER: /run/secrets/synology_user
      HOMEPAGE_FILE_SYNOLOGY_PASS: /run/secrets/synology_pass
      HOMEPAGE_FILE_OCTOPRINT_KEY: /run/secrets/octoprint_key
      HOMEPAGE_FILE_PROWLARR_KEY: /run/secrets/prowlarr_key
      HOMEPAGE_FILE_TRANSMISSION_USER: /run/secrets/transmission_user
      HOMEPAGE_FILE_TRANSMISSION_PASS: /run/secrets/transmission_pass
      HOMEPAGE_FILE_SABNZBD_KEY: /run/secrets/sabnzbd_key
    volumes:
      - ./config:/app/config
    ports:
      - 3000:3000
    secrets:
      - tautulli_key
      - radarr_key
      - sonarr_key
      - bazarr_key
      - synology_user
      - synology_pass
      - octoprint_key
      - prowlarr_key
      - transmission_user
      - transmission_pass
      - sabnzbd_key

      
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    restart: unless-stopped
    environment:
      - CONTAINERS=1
      - SERVICES=1
      - TASKS=1
      - POST=0
    ports:
      - 127.0.0.1:2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

secrets:
  tautulli_key:
    file: ./secrets/tautulli_key.txt
  radarr_key:
    file: ./secrets/radarr_key.txt
  sonarr_key:
    file: ./secrets/sonarr_key.txt
  bazarr_key:
      file: ./secrets/bazarr_key.txt
  synology_user:
      file: ./secrets/synology_user.txt
  synology_pass:
      file: ./secrets/synology_pass.txt
  octoprint_key:
      file: ./secrets/octoprint_key.txt
  prowlarr_key:
      file: ./secrets/prowlarr_key.txt
  transmission_user:
      file: ./secrets/transmission_user.txt
  transmission_pass:
      file: ./secrets/transmission_pass.txt
  sabnzbd_key:
      file: ./secrets/sabnzbd_key.txt