include:
  - ../common/networks.yaml

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    environment:
      LOG_TARGETS: stdout
      HOMEPAGE_ALLOWED_HOSTS: homepage.sdf1.site
      HOMEPAGE_FILE_BAZARR_KEY: /run/secrets/bazarr_key
      HOMEPAGE_FILE_CALIBRE_PASS: /run/secrets/calibre_pass
      HOMEPAGE_FILE_NPM_PASS: /run/secrets/npm_pass
      HOMEPAGE_FILE_PAPERLESS_KEY: /run/secrets/paperless_key
      HOMEPAGE_FILE_PLEX_KEY: /run/secrets/plex_key
      HOMEPAGE_FILE_PROWLARR_KEY: /run/secrets/prowlarr_key
      HOMEPAGE_FILE_RADARR_KEY: /run/secrets/radarr_key
      HOMEPAGE_FILE_SABNZBD_KEY: /run/secrets/sabnzbd_key
      HOMEPAGE_FILE_SONARR_KEY: /run/secrets/sonarr_key
      HOMEPAGE_FILE_SYNOLOGY_PASS: /run/secrets/synology_pass
      HOMEPAGE_FILE_SYNOLOGY_USER: /run/secrets/synology_user
      HOMEPAGE_FILE_TAILSCALE_KEY: /run/secrets/tailscale_key
      HOMEPAGE_FILE_TAUTULLI_KEY: /run/secrets/tautulli_key
      HOMEPAGE_FILE_TRANSMISSION_USER: /run/secrets/transmission_user
      HOMEPAGE_FILE_TRANSMISSION_PASS: /run/secrets/transmission_pass
      HOMEPAGE_FILE_TRUENAS_KEY: /run/secrets/truenas_key
      HOMEPAGE_FILE_UNIFI_UCG_MAX_KEY: /run/secrets/unifi_ucg_max_key
      HOMEPAGE_FILE_HOMEBOX_USER: /run/secrets/homebox_user
      HOMEPAGE_FILE_HOMEBOX_PASS: /run/secrets/homebox_pass
      HOMEPAGE_FILE_PROXMOX_USER: /run/secrets/proxmox_token_id
      HOMEPAGE_FILE_PROXMOX_PASS: /run/secrets/proxmox_token
      HOMEPAGE_FILE_HA_TOKEN: /run/secrets/homeassistant_token
    volumes:
      - type: volume
        source: data
        target: /app/config
        volume:
          nocopy: true
          subpath: homepage/config
    networks:
      - default
      - homelab
    secrets:
      - bazarr_key
      - calibre_pass
      - npm_pass
      - paperless_key
      - plex_key
      - prowlarr_key
      - radarr_key
      - sabnzbd_key
      - sonarr_key
      - synology_pass
      - synology_user
      - tailscale_key
      - tautulli_key
      - transmission_pass
      - transmission_user
      - truenas_key
      - unifi_ucg_max_key
      - homebox_user
      - homebox_pass
      - proxmox_token_id
      - proxmox_token
      - homeassistant_token
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: homepage-dockerproxy
    restart: unless-stopped
    environment:
      - CONTAINERS=1
      - SERVICES=1
      - TASKS=1
      - POST=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - default

secrets:
  bazarr_key:
    file: /etc/homelab/homepage/secrets/bazarr_key
  calibre_pass:
    file: /etc/homelab/homepage/secrets/calibre_pass
  npm_pass:
    file: /etc/homelab/homepage/secrets/npm_pass
  paperless_key:
    file: /etc/homelab/homepage/secrets/paperless_key
  plex_key:
    file: /etc/homelab/homepage/secrets/plex_key
  prowlarr_key:
    file: /etc/homelab/homepage/secrets/prowlarr_key
  radarr_key:
    file: /etc/homelab/homepage/secrets/radarr_key
  sabnzbd_key:
    file: /etc/homelab/homepage/secrets/sabnzbd_key
  sonarr_key:
    file: /etc/homelab/homepage/secrets/sonarr_key
  synology_pass:
    file: /etc/homelab/homepage/secrets/synology_pass
  synology_user:
    file: /etc/homelab/homepage/secrets/synology_user
  tailscale_key:
    file: /etc/homelab/homepage/secrets/tailscale_key
  tautulli_key:
    file: /etc/homelab/homepage/secrets/tautulli_key
  transmission_pass:
    file: /etc/homelab/homepage/secrets/transmission_pass
  transmission_user:
    file: /etc/homelab/homepage/secrets/transmission_user
  truenas_key:
    file: /etc/homelab/homepage/secrets/truenas_key
  unifi_ucg_max_key:
    file: /etc/homelab/homepage/secrets/unifi_ucg_max_key
  homebox_user:
    file: /etc/homelab/homepage/secrets/homebox_user
  homebox_pass:
    file: /etc/homelab/homepage/secrets/homebox_pass
  proxmox_token_id:
    file: /etc/homelab/homepage/secrets/proxmox_token_id
  proxmox_token:
    file: /etc/homelab/homepage/secrets/proxmox_token
  homeassistant_token:
    file: /etc/homelab/homepage/secrets/homeassistant_token

networks:
  default:

volumes:
  data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=terminal-dogma.local,nolock,soft,nfsvers=4
      device: :/mnt/DataPool/AppData
