services:
  yacht:
    container_name: yacht
    image: selfhostedpro/yacht
    restart: unless-stopped
    environment:
      - PUID=3000
      - PGID=3000
    ports:
      - 8000:8000
    volumes:
      - type: volume
        source: app-configs
        target: /config
        volume:
          nocopy: true
          subpath: yacht/config
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  app-configs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=terminal-dogma.local,nolock,soft,nfsvers=4
      device: :/mnt/Storage Pool 1/AppConfigs