include:
  - ../common/networks.yaml
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"
    volumes:
      - ./conf.d/:/etc/nginx/conf.d/:ro
      - /var/www/certbot/:/var/www/certbot/:ro
      - /etc/letsencrypt/:/etc/nginx/ssl/:ro
    networks:
      - homelab
    healthcheck:
      test: curl --fail http://localhost/ping || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '8080:80' # Public HTTP Port
      - '8443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"
    environment:
      PUID: 1000
      PGID: 1000
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_NAME: "npm"
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD__FILE: /run/secrets/MYSQL_PWD
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt
      - type: volume
        source: config
        target: /data
        volume:
          nocopy: true
          subpath: npm/data
    networks:
      - homelab
    depends_on:
      - db
    secrets:
      - MYSQL_PWD
  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    user: "1000:1000"
    environment:
      MARIADB_AUTO_UPGRADE: '1'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_ROOT_PASSWORD__FILE: /run/secrets/DB_ROOT_PWD
      MYSQL_PASSWORD__FILE: /run/secrets/MYSQL_PWD
    volumes:
      - type: volume
        source: config
        target: /var/lib/mysql
        volume:
          nocopy: true
          subpath: npm/db
    secrets:
      - DB_ROOT_PWD
      - MYSQL_PWD

secrets:
  DB_ROOT_PWD:
    file: /etc/homelab/npm/secrets/db_root_pass
  MYSQL_PWD:
    file: /etc/homelab/npm/secrets/db_pass

volumes:
  config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=terminal-dogma.local,nolock,soft,nfsvers=4
      device: :/mnt/AppDataPool/Configs