include:
  - ../common/networks.yaml

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    ports:
      - 7878:7878
    volumes:
      - /etc/servarr/radarr/config:/config
      - central-dogma:/data
    networks:
      - homelab
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    ports:
      - 8989:8989
    volumes:
      - /etc/servarr/sonarr/config:/config
      - central-dogma:/data
    networks:
      - homelab
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    ports:
      - 6767:6767
    volumes:
      - /etc/servarr/bazarr/config:/config
      - central-dogma:/data
    networks:
      - homelab
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    ports:
      - 9696:9696
    volumes:
      - /etc/servarr/prowlarr:/config
    networks:
      - homelab
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    ports:
      - 8080:8080
    volumes:
      - /etc/servarr/sabnzbd:/config
      - central-dogma:/data
    networks:
      - homelab
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    env_file: /etc/homelab/transmission.env
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - /etc/servarr/transmission:/config
      - central-dogma:/data
    networks:
      - homelab

volumes:
  central-dogma:
    driver: local
    driver_opts:
      type: nfs
      o: addr=central-dogma.local,nolock,soft,nfsvers=4
      device: :/volume1/Media
