include:
  - ../common/networks.yaml

services:
  db:
    image: postgres:14
    container_name: servarr-db
    restart: unless-stopped
    user: "1000:1000"
    environment:
      POSTGRES_USER: servarr
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
    volumes:
      - type: volume
        source: config
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
          subpath: servarr/postgres14
    networks:
      - default
    secrets:
      - POSTGRES_PASSWORD
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: always
    depends_on:
      - db
    env_file: /etc/homelab/servarr/radarr.env
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Los_Angeles
      RADARR__POSTGRES__HOST: db
      RADARR__POSTGRES__PORT: 5432
      RADARR__POSTGRES__USER: servarr
    volumes:
      - central-dogma:/data
      - type: volume
        source: config
        target: /config
        volume:
          nocopy: true
          subpath: radarr/config
    networks:
      - default
      - homelab
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - central-dogma:/data
      - type: volume
        source: config
        target: /config
        volume:
          nocopy: true
          subpath: sonarr/config
    networks:
      - default
      - homelab
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - central-dogma:/data
      - type: volume
        source: config
        target: /config
        volume:
          nocopy: true
          subpath: bazarr/config
    networks:
      - default
      - homelab
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: always
    depends_on:
      - db
    env_file: /etc/homelab/servarr/prowlarr.env
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Los_Angeles
      PROWLARR__POSTGRES__HOST: db
      PROWLARR__POSTGRES__PORT: 5432
      PROWLARR__POSTGRES__USER: servarr
    volumes:
      - type: volume
        source: config
        target: /config
        volume:
          nocopy: true
          subpath: prowlarr/config
    networks:
      - default
      - homelab
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - type: volume
        source: config
        target: /config
        volume:
          nocopy: true
          subpath: sabnzbd/config
      - central-dogma:/data
    networks:
      - default
      - homelab
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    env_file: /etc/homelab/transmission.env
    ports:
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - central-dogma:/data
      - type: volume
        source: config
        target: /config
        volume:
          nocopy: true
          subpath: transmission/config
    networks:
      - default
      - homelab

volumes:
  config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=terminal-dogma.local,nolock,soft,nfsvers=4
      device: :/mnt/DataPool/AppData

  central-dogma:
    driver: local
    driver_opts:
      type: nfs
      o: addr=central-dogma.local,nolock,soft,nfsvers=4
      device: :/volume1/Media

secrets:
  POSTGRES_PASSWORD:
    file: /etc/homelab/servarr/secrets/db_pass

networks:
  default: