include:
  - ../common/networks.yaml

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - central-dogma:/data
      - type: volume
        source: data
        target: /config
        volume:
          nocopy: true
          subpath: radarr/config
    networks:
      - default
      - homelab
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - central-dogma:/data
      - type: volume
        source: data
        target: /config
        volume:
          nocopy: true
          subpath: sonarr/config
    networks:
      - default
      - homelab
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - central-dogma:/data
      - type: volume
        source: data
        target: /config
        volume:
          nocopy: true
          subpath: bazarr/config
    networks:
      - default
      - homelab
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - type: volume
        source: data
        target: /config
        volume:
          nocopy: true
          subpath: prowlarr/config
    networks:
      - default
      - homelab
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - type: volume
        source: data
        target: /config
        volume:
          nocopy: true
          subpath: sabnzbd/config
      - central-dogma:/data
    networks:
      - default
      - homelab
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    env_file: /etc/homelab/transmission.env
    ports:
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - central-dogma:/data
      - type: volume
        source: data
        target: /config
        volume:
          nocopy: true
          subpath: transmission/config
    networks:
      - default
      - homelab

volumes:
  app-data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=terminal-dogma.local,nolock,soft,nfsvers=4
      device: :/mnt/DataPool/AppData

  central-dogma:
    driver: local
    driver_opts:
      type: nfs
      o: addr=central-dogma.local,nolock,soft,nfsvers=4
      device: :/volume1/Media

networks:
  default: