# yamllint disable rule:comments-indentation
---
certificates_directory: '/config/certificates/'

## The theme to display: light, dark, grey, auto.
theme: 'auto'

## Set the default 2FA method for new users and for when a user has a preferred 
## method configured that has been disabled. This setting must be a method that 
## is enabled.
## Options are totp, webauthn, mobile_push.
default_2fa_method: 'webauthn'

server:
  address: 'tcp://:9091/'
  asset_path: '/config/assets/'
  disable_healthcheck: false

log:
  ## Level of verbosity for logs: info, debug, trace.
  level: 'debug'
  format: 'json'
  ## Whether to also log to stdout when a log_file_path is defined.
  keep_stdout: true
  ## File path where the logs will be written. If not set logs are written 
  ## to stdout.
  # file_path: '/config/authelia.log'

totp:
  ## Disable TOTP.
  disable: false
  issuer: 'auth.sdf1.rampant.io'
  algorithm: 'SHA1'
  digits: 6
  period: 30

webauthn:
  disable: true
  enable_passkey_login: true
  ## The display name the browser should show the user for when using WebAuthn 
  ## to login/register.
  # display_name: 'Authelia'
  attestation_conveyance_preference: 'direct'
  filtering:
    prohibit_backup_eligibility: false
  metadata:
    enabled: true
    validate_trust_anchor: true
    validate_entry: true
    validate_entry_permit_zero_aaguid: false
    validate_status: true

identity_validation:
  ## Reset Password flow. Adjusts how the reset password flow operates.
  reset_password:
    ## Maximum allowed time before the JWT is generated and when the user uses it in the duration common syntax.
    jwt_lifespan: '5 minutes'
    ## The algorithm used for the Reset Password JWT.
    jwt_algorithm: 'HS256'

  ## Elevated Session flows. Adjusts the flow which require elevated sessions for example managing credentials, adding,
  ## removing, etc.
  elevated_session:
    ## Maximum allowed lifetime after the One-Time Code is generated that it is considered valid.
    code_lifespan: '5 minutes'
    ## Maximum allowed lifetime after the user uses the One-Time Code and the user must perform the validation again in
    ## the duration common syntax.
    elevation_lifespan: '10 minutes'
    ## Number of characters the one-time password contains.
    characters: 8
    ## In addition to the One-Time Code requires the user performs a second factor authentication.
    require_second_factor: false
    ## Skips the elevation requirement and entry of the One-Time Code if the user has performed second factor
    ## authentication.
    skip_second_factor: false

ntp:
  address: 'udp://time.cloudflare.com:123'
  version: 4
  max_desync: '3 seconds'
  disable_startup_check: false
  disable_failure: false

##
## Definitions
##
## The definitions are used in other areas as reference points to reduce duplication.
##
# definitions:
  ## The user attribute definitions.
  # user_attributes:
    ## The name of the definition.
    # definition_name:
      ## The common expression language expression for this definition.
      # expression: ''

  ## The network definitions.
  # network:
    ## The name of the definition followed by the list of CIDR network addresses in this definition.
    # internal:
      # - '10.10.0.0/16'
      # - '172.16.0.0/12'
      # - '192.168.2.0/24'
    # VPN:
      # - '10.9.0.0/16'

authentication_backend:
  password_change:
    ## Disable both the HTML element and the API for password change functionality.
    disable: false
  password_reset:
    ## Disable both the HTML element and the API for reset password functionality.
    disable: false
  # Cost of this is negligible with file provider.
  # Change this for LDAP
  refresh_interval: 'always'
  ldap:
    address: 'ldap://lldap:3890'
    implementation: 'lldap'
    timeout: '5s'
    base_dn: 'dc=sdf1,dc=rampant.io'
    additional_users_dn: 'ou=people'
    additional_groups_dn: 'ou=groups'
    user: 'cn=observer,ou=people,dc=sdf1,dc=rampant.io'

password_policy:
  zxcvbn:
    enabled: true
    min_score: 3

access_control:
  default_policy: 'one_factor'

session:
  ## Cookie Session Domain default 'name' value.
  name: 'authelia_session'
  # same_site: 'lax'
  # inactivity: '5m'
  # expiration: '1h'
  # remember_me: '1M'
  ## Cookies configures the list of allowed cookie domains for sessions to be created on.
  ## Undefined values will default to the values below.
  cookies:
      ## The name of the session cookie.
    - domain: 'sdf1.rampant.io'
      authelia_url: 'https://auth.sdf1.rampant.io'

## This mechanism prevents attackers from brute forcing the first factor. It bans the user if too many attempts are made
## in a short period of time.
regulation:
  ## Regulation Mode.
  modes:
    - 'ip'
  max_retries: 5
  ## The time range during which the user can attempt login before being banned in the duration common syntax. The user
  ## is banned if the authentication failed 'max_retries' times in a 'find_time' seconds window.
  find_time: '2 minutes'
  ## The length of time before a banned user can login again in the duration common syntax.
  ban_time: '10 minutes'

storage:
  local:
    ## Path to the SQLite3 Database.
    path: '/config/db.sqlite3'

notifier:
  ## You can disable the notifier startup check by setting this to true.
  disable_startup_check: false
  smtp:
    address: 'smtp://smtp.fastmail.com:587'
    timeout: '5s'
    username: 'jonathan@borzilleri.net'
    sender: "Authelia <authelia@rampant.io>"
  #filesystem:
  #  filename: '/config/notification.txt'

identity_providers:
  oidc:
    enable_client_debug_messages: false
    lifespans:
      access_token: '1 hour'
      authorize_code: '1 minute'
      id_token: '1 hour'
      refresh_token: '90 minutes'

    jwks:
      - algorithm: 'RS256'
        use: 'sig'
        key: {{ secret "/run/secrets/authelia_oidc_jwks_rsa_2048_private_pem" | mindent 10 "|" | msquote }}

    clients:
      - client_name: 'Paperless'
        client_id: 'paperless'
        client_secret: {{ secret "/run/secrets/authelia_paperless_client_secret" | mindent 10 "|" | msquote }}
        public: false
        authorization_policy: 'two_factor'
        require_pkce: true
        pkce_challenge_method: 'S256'
        redirect_uris:
          - 'https://paperless.sdf1.rampant.io/accounts/oidc/authelia/login/callback/'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
          - 'groups'
        response_types:
          - 'code'
        grant_types:
          - 'authorization_code'
        access_token_signed_response_alg: 'none'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_basic'
