---
- Personal:
    - Rampant I/O:
        - abbr: IO
          href: https://rampant.io
    - Borzilleri.net:
        - abbr: JB
          href: https://borzilleri.net

- Developer:
    - AWS:
        - icon: sh-amazon-web-services-light
          href: https://rampantio.signin.aws.amazon.com/console/
    - Github:
        - icon: sh-github-light
          href: https://github.com/borzilleri/
    - Tailscale:
        - icon: sh-tailscale-light
          href: https://login.tailscale.com/admin/machines
