- Media:
  - Mealie:
      icon: sh-mealie-light
      href: http://mealie.sdf1.site
      server: melchior
      container: mealie
      widget:
        type: mealie
        url: http://mealie:9000
        key: {{HOMEPAGE_FILE_MEALIE_KEY}}
        version: 2 
  - Paperless:
      icon: sh-paperless-ngx-light
      href: http://paperless.sdf1.site
      server: melchior
      container: paperless-webserver
      widget:
        type: paperlessngx
        url: http://paperless-webserver:8000
        key: {{HOMEPAGE_FILE_PAPERLESS_KEY}}
  - Kavita:
      icon: sh-kavita
      href: http://kavita.sdf1.site
      server: melchior
      container: kavita
      widget:
        type: kavita
        url: http://kavita:5000
        username: {{HOMEPAGE_FILE_KAVITA_USER}}
        password: {{HOMEPAGE_FILE_KAVITA_PASS}}
  - Plex:
      icon: sh-plex
      href: https://app.plex.tv
      widget:
        type: tautulli
        url: http://caspar.tail120b6.ts.net:8181
        key: {{HOMEPAGE_FILE_TAUTULLI_KEY}}
  - Radarr:
      icon: sh-radarr-light
      href: http://radarr.sdf1.site
      server: melchior
      container: radarr
      widget:
        type: radarr
        url: http://radarr:7878
        key: {{HOMEPAGE_FILE_RADARR_KEY}}
  - Sonarr:
      icon: sh-sonarr
      href: http://sonarr.sdf1.site
      server: melchior
      container: sonarr
      widget:
        type: sonarr
        url: http://sonarr:8989
        key: {{HOMEPAGE_FILE_SONARR_KEY}}

- Services:
  - Bazarr:
      icon: sh-bazarr
      href: http://bazarr.sdf1.site
      server: melchior
      container: bazarr
      widget:
        type: bazarr
        url: http://bazarr:6767
        key: {{HOMEPAGE_FILE_BAZARR_KEY}}
  - Prowlarr:
      icon: sh-prowlarr
      href: http://prowlarr.sdf1.site
      server: melchior
      container: prowlarr
      widget:
        type: prowlarr
        url: http://prowlarr:9696
        key: {{HOMEPAGE_FILE_PROWLARR_KEY}}
  - SABnzbd:
      icon: sh-sabnzbd
      href: http://sabnzbd.sdf1.site
      server: melchior
      container: sabnzbd
      widget:
        type: sabnzbd
        url: http://sabnzbd:8080
        key: {{HOMEPAGE_FILE_SABNZBD_KEY}}
  - Transmission:
      icon: sh-transmission
      href: http://transmission.sdf1.site
      server: melchior
      container: transmission
      widget:
        type: transmission
        url: http://transmission:9091
        username: {{HOMEPAGE_FILE_TRANSMISSION_USER}}
        password: {{HOMEPAGE_FILE_TRANSMISSION_PASS}}
  - FoundryVTT:
      icon: sh-foundry-virtual-tabletop
      href: https://foundry.rampant.io
      siteMonitor: https://foundry.rampant.io
      widget:
        type: customapi
        url: https://foundry.rampant.io/api/status
        refreshInterval: 60000
        method: GET
        mappings:
          - field: active
            label: STATUS
            remap:
              - value: true
                to: Running
              - value: false
                to: Inactive
          - field: users
            label: PLAYERS
            format: text
          - field: version
            label: VERSION

- Tailscale:
  - Central-Dogma:
      icon: sh-synology-light
      widget:
        type: tailscale
        deviceid: ndWSpYRefZ11CNTRL
        key: {{HOMEPAGE_FILE_TAILSCALE_KEY}}
  - Caspar:
      icon: sh-apple-light
      widget:
        type: tailscale
        deviceid: nrUQEf2CNTRL
        key: {{HOMEPAGE_FILE_TAILSCALE_KEY}}
  - Melchior:
      icon: sh-debian
      widget:
        type: tailscale
        deviceid: nk3yA1S1Gk11CNTRL
        key: {{HOMEPAGE_FILE_TAILSCALE_KEY}}
  - Cloudbank:
      icon: sh-microsoft-windows-light
      widget:
        type: tailscale
        deviceid: nyGBArTHSp11CNTRL
        key: {{HOMEPAGE_FILE_TAILSCALE_KEY}}
  - SDF-1:
      icon: sh-apple-light
      widget:
        type: tailscale
        deviceid: n3p2cA6CNTRL
        key: {{HOMEPAGE_FILE_TAILSCALE_KEY}}

- Data & Network:
  - Unifi Express:
      icon: sh-ubiquiti-unifi-light
      href: https://unifi.ui.com/consoles/942A6F1A68D80000000008133FD3000000000880E6FB00000000664E63BD:1105048/network/default/dashboard
      widget:
        type: unifi
        url: https://192.168.1.1
        username: {{HOMEPAGE_FILE_UNIFI_USER}}
        password: {{HOMEPAGE_FILE_UNIFI_PASS}}
        fields: ["uptime", "wan", "lan_devices", "wlan_devices"]
  - Synology:
      icon: sh-synology-light
      href: http://central-dogma:5000
      widget:
        type: diskstation
        url: http://central-dogma.tail120b6.ts.net:5000
        username: {{HOMEPAGE_FILE_SYNOLOGY_USER}}
        password: {{HOMEPAGE_FILE_SYNOLOGY_PASS}}
  - TrueNAS:
      icon: sh-truenas-scale-light
      href: http://truenas
      widget:
        type: truenas
        url: http://terminal-dogma.local
        key: {{HOMEPAGE_FILE_TRUENAS_KEY}}
        enablePools: true
        nasType: scale

- Devices:
  - HDHomeRun:
      icon: sh-hdhomerun
      href: http://hdhomerun.sdf1.site
      widget:
        type: hdhomerun
        url: http://192.168.1.246
        fields: ["channels", "hd"]
  - Octoprint:
      icon: sh-octoprint
      href: http://octopi.sdf1.site
      widget:
        type: octoprint
        url: http://octopi.local
        key: {{HOMEPAGE_FILE_OCTOPRINT_KEY}}
