- Media:
  - Plex:
      icon: sh-plex
      href: https://app.plex.tv
      widget:
        type: tautulli
        url: http://caspar.tail120b6.ts.net:8181
        key: {{HOMEPAGE_FILE_TAUTULLI_KEY}}
  - Radarr:
      icon: sh-radarr
      href: http://radarr
      server: melchior
      container: radarr
      widget:
        type: radarr
        url: http://radarr
        key: {{HOMEPAGE_FILE_RADARR_KEY}}
  - Sonarr:
      icon: sh-sonarr
      href: http://sonarr
      server: melchior
      container: sonarr
      widget:
        type: sonarr
        url: http://sonarr
        key: {{HOMEPAGE_FILE_SONARR_KEY}}
  - Bazarr:
      icon: sh-bazarr
      href: http://bazarr
      server: melchior
      container: bazarr
      widget:
        type: bazarr
        url: http://bazarr
        key: {{HOMEPAGE_FILE_BAZARR_KEY}}

- Data & Network:
  # - Tailscale:
  # - Paperless-ngx:
  - Synology:
      icon: sh-synology
      href: http://central-dogma:5000
      widget:
        type: diskstation
        url: http://central-dogma:5000
        username: {{HOMEPAGE_FILE_SYNOLOGY_USER}}
        password: {{HOMEPAGE_FILE_SYNOLOGY_PASS}}
        #volume: volume_N
#  - TrueNas:

- Devices:
  - Octoprint:
      icon: sh-octoprint
      href: http://octopi
      widget:
        type: octoprint
        url: http://octopi
        key: {{HOMEPAGE_FILE_OCTOPRINT_KEY}}

- Backend:
  - Prowlarr:
      icon: sh-prowlarr
      href: http://prowlarr
      server: melchior
      container: prowlarr
      widget:
        type: prowlarr
        url: http://prowlarr
        key: {{HOMEPAGE_FILE_PROWLARR_KEY}}
  - Transmission:
      icon: sh-transmission
      href: http://transmission
      server: melchior
      container: transmission
      widget:
        type: transmission
        url: http://transmission
        username: {{HOMEPAGE_FILE_TRANSMISSION_USER}}
        password: {{HOMEPAGE_FILE_TRANSMISSION_PASS}}
  - SABnzbd:
      icon: sh-sabnzbd
      url: http://sabnzbd
      server: melchior
      container: sabnzbd
      widget:
        type: sabnzbd
        url: http://sabnzbd
        key: {{HOMEPAGE_FILE_SABNZBD_KEY}}
  - HDHomeRun:
      icon: sh-hdhomerun
      url: http://192.168.1.246

