---
title: SDF-1.site
theme: dark
color: slate
target: _blank
showStats: true
statusStyle: "dot"
useEqualHeights: true

layout:
  Links:
  Media:
    style: row
    columns: 3
  Devices:
    style: row
    columns: 3
  "Data & Network":
    style: row
    columns: 3
  Services:
    style: row
    columns: 3
  Tailscale:
    style: row
    columns: 3

