---
title: SDF-1.site
theme: dark
color: slate
target: _blank
showStats: true
statusStyle: "dot"

layout:
  Media:
    style: row
  Servarr:
    style: row
    columns: 3
  Tailscale:
    columns: 3
  Data & Networks:
  Devices:

