---
title: SDF-1.site
theme: dark
color: slate
target: _blank
showStats: true
statusStyle: "dot"

layout:
  Media:
    style: row
    columns: 3
  Devices:
    style: row
    columns: 3
  Data & Network:
    style: row
    useEqualHeights: true
  Services:
    style: row
    columns: 3
    useEqualHeights: true
  Tailscale:
    style: row
    columns: 3

