---
- resources:
    cpu: true
    memory: true
    disk: /

- openmeteo:
    label: Seattle
    latitude: 47.60764678870511
    longitude: -122.32772055715245
    timezone: America/Los_Angeles
    units: imperial
    cache: 10
    format:
      maximumFractionDigits: 1

- search:
    provider: duckduckgo
    target: _blank

